### ISSUE TITLE
Join field (instead of object) to schema

### ISSUE THREAD

**Issue by idangozlan** [join-monster/join-monster#227] opened 2017-09-05 10:17 UTC
Is there any way to join non object (string) to schema?

All I can see on the docs is about [Joining objects](https://join-monster.readthedocs.io/en/latest/start-joins/) but I need to join single field (string) from another table.

Thanks

**Comment by acarl005** [comment] 2017-09-06 05:25
Ah yes, this is a similar issue to #57. Although in that case a workaround was found, I think this functionality may need to be a first-class citizen. This feature needs to be reconsidered.

**Comment by idangozlan** [comment] 2017-09-06 07:50
Thanks, I can try help implement it.

**Comment by horakmx** [comment] 2018-05-09 13:45
Same problem is discussed here: #311, #198

**Comment by nicoabie** [comment] 2024-05-05 20:59
Closing as duplicate of #198

**Closed as completed by nicoabie** 2024-05-05 20:59 UTC
Labels: duplicate
