### ISSUE TITLE
MySQL Limit - Offset for pagination Support

### ISSUE THREAD

**Issue by abodehq** [join-monster/join-monster#354] opened 2018-10-18 04:49 UTC
Dears ,,

its really an amazing library, thanks for the great effort, but i am not able to add pagination for Mysql db which is as i think itis not supported by your library.

so pleaaaaaaaaaaaaase can you let me know if you can fix this issue asap.

thaaaaaaaaaaaaanks.
abed_q@hotmail.com

**Comment by GlennMatthys** [comment] 2018-11-03 06:48
Duplicate of #280 #281 #247 #243. We are working on this, please see the [API proposal in the wiki](https://github.com/acarl005/join-monster/wiki/Proposal:-manual-OFFSET-LIMIT-control).

**Comment by nicoabie** [comment] 2024-05-05 14:09
Closing as marked as duplicate.

**Closed as completed by nicoabie** 2024-05-05 14:09 UTC
Labels: duplicate
